neo4j-transaction-scope-cache is a set of neo4j stored procedures to provide a cache being local to the current transaction.

== usage

There are basically a `put(key,value)` and a `get(key)` procedure or user defined function to access the cache.

For a programmatic usage in your own procedures / UDFs you need to have a

[source,java]
-----
@Context
public KernelTransaction kernelTransaction
-----

as a injected component.

WARNING: Having a `KernelTransaction` as a injected component requires these procedures to be configured as unrestricted. Amend `dbms.security.procedures.unrestricted=org.neo4j.contrib.txcache.*` to your `neo4j.conf` to do this.

Your code then uses the following snippet:
[source,java]
-----
@Procedure
public Stream<Something> myProcs(...params...) {
    Map<String,Object> cache = TxCacheFunctions.getCache(kernelTransaction);
}
-----

The implementation of the cache logic is as follows:

 . the `startTime` of the transaction is stored in a `ThreadLocal`, initially we use `-1`
 . if the `startTime` of the current transaction is different from the `ThreadLocal` 's value a new cache is initialized and also stored as second `ThreadLocal`
 . if the `startTime` is equals to the one in the `ThreadLocal` the existing cache is used.

Cypher usage examples can be found in the link:src/test/java/org/neo4j/contrib/txcache/TxCacheFunctionsTest.java[unit tests].
